<?php
require("../../inc/header.php");

/*
		SoftName : EmpireBak Version 2010
		Author   : wm_chief
		Copyright: Powered by www.phome.net
*/

DoSetDbChar('utf8');
E_D("DROP TABLE IF EXISTS `ld_news_data`;");
E_C("CREATE TABLE `ld_news_data` (
  `id` mediumint(8) unsigned default '0',
  `content` mediumtext NOT NULL,
  `readpoint` smallint(5) unsigned NOT NULL default '0',
  `groupids_view` varchar(100) NOT NULL,
  `paginationtype` tinyint(1) NOT NULL,
  `maxcharperpage` mediumint(6) NOT NULL,
  `template` varchar(30) NOT NULL,
  `paytype` tinyint(1) unsigned NOT NULL default '0',
  `relation` varchar(255) NOT NULL default '',
  `voteid` mediumint(8) unsigned NOT NULL default '0',
  `allow_comment` tinyint(1) unsigned NOT NULL default '1',
  `copyfrom` varchar(100) NOT NULL default '',
  KEY `id` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8");
E_D("replace into `ld_news_data` values('1','<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 5月17日下午14:00-16:00 &ldquo;KI树德教育&rdquo;总裁兼董事长受邀校宝学院参加网略在线直播课程！<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;本次演讲主题为《招生中市场工作流程的设计》，其中全国的1000多名教育培训机构负责人兼校长聆听了本次的在线直播课程。凭借自己多年在市场中的实战经验KI总裁李老师主要就招生中存在的问题分享了自己的想法，并提供了一些意见和建议。<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 李老师是原某上市公司营销总监及商学院创始人，而且是国内管理培训泰斗余世维老师的首批弟子，现任多家企业特聘营销咨询顾问。本次直播课程虽然时间暂短，但内容丰富多彩，设计多个学科领域，包括日常生活中的与人沟通、日常生活交际礼仪、多场面灵活应对方式方法以及心理学、市场管理等方面，同时洞悉公司人事、薪酬、激励/考核及文化价值观等纯干货，有警示醒言等良句之姿。<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 校宝学院表示之后将会同李老师进行深度合作，期望在该平台上能展示出更多有关李老师的肺腑分享。下期系列李老师表示会很乐意在校宝平台上向广大校友聊一些相关的碎碎念，届时希望大家踊跃关注、相互沟通交流。</p>\r\n<p><br />\r\n<br />\r\n<strong><span mso-ansi-language:=\"\" mso-bidi-font-family:=\"\" mso-bidi-language:=\"\" mso-bidi-theme-font:=\"\" mso-fareast-language:=\"\" mso-font-kerning:=\"\" new=\"\" style=\"font-size: 9pt\" times=\"\"><font color=\"#000000\">注：</font></span><em><span mso-ansi-language:=\"\" mso-bidi-font-family:=\"\" mso-bidi-language:=\"\" mso-fareast-language:=\"\" mso-font-kerning:=\"\" style=\"font-size: 9pt\"><font color=\"#cc0000\">校宝学院</font></span></em><span color:=\"\" mso-ansi-language:=\"\" mso-bidi-font-family:=\"\" mso-bidi-language:=\"\" mso-fareast-language:=\"\" mso-font-kerning:=\"\" style=\"font-size: 9pt\">是基于互联网<span lang=\"EN-US\">[</span>免费、知识共享与碎片化学习<span lang=\"EN-US\">]</span>精神，连接<span lang=\"EN-US\">120000</span>多位培训机构校长和<span lang=\"EN-US\">350000</span>多位培训机构管理人员的免费在线直播课程</span></strong></p>\r\n','0','','0','0','','0','','0','1','|0');");
E_D("replace into `ld_news_data` values('2','&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 4月初，当大家还在享受春天咋暖还寒的气候时，KI机器人又蠕蠕出洞了！一举签约了重庆优胜教育培训机构。双方就KI机器人正式入住重庆少儿优胜达成一致协议。同时聘请KI总裁李金昊担任重庆优胜教育机构常年营销顾问。就其未来的市场营销进行指导培训。<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 重庆优胜教育是专注于中小学学习指导的一对一教育培训机构。此次重庆少儿优胜教育引入了KI机器人初级课程之后，在5月份的招生统计中，平均客户到店量较4月份提高了4倍，除了KI机器人本身课程吸引了大量粉丝外，KI机器人初级课程的引进还为该机构主营业务增加了大量的销量，例如，奥数、语文以及数学课程等等也吸粉无数！业绩创新高！','0','','0','0','','0','','0','1','|0');");
E_D("replace into `ld_news_data` values('3','<span style=\"font-size: 14px\"><span style=\"font-family: 微软雅黑\"><span mso-ansi-language:=\"\" mso-bidi-language:=\"\" mso-bidi-theme-font:=\"\" mso-fareast-language:=\"\" mso-font-kerning:=\"\" new=\"\" times=\"\"><font color=\"#000000\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 市场上大部分企业往往重&ldquo;售前&rdquo;、轻&ldquo;售后&rdquo;，售前服务虽然做的很好，但售后服务容易忽略种种微小的细节，且因为各种各样的因素，比如公司机制、员工态度等导致了客户对产品不满意，大大降低了客户对公司的好感度，从而致使客户的流失率过高。同时在<span lang=\"EN-US\">&ldquo;</span></font><font color=\"#000000\">售前</font><span lang=\"EN-US\"><font color=\"#000000\">&rdquo;</font></span><font color=\"#000000\">时对客户过度承诺商品的实用性、便利性等等，导致</font><span lang=\"EN-US\"><font color=\"#000000\">&ldquo;</font></span><font color=\"#000000\">使用前</font><span lang=\"EN-US\"><font color=\"#000000\">&rdquo;</font></span><font color=\"#000000\">和</font><span lang=\"EN-US\"><font color=\"#000000\">&ldquo;</font></span><font color=\"#000000\">使用后</font><span lang=\"EN-US\"><font color=\"#000000\">&rdquo;</font></span><font color=\"#000000\">心理体验落差较大，继而也严重影响了客户再次&ldquo;续费&rdquo;。</font></span></span></span>','0','','0','0','','0','','0','1','|0');");
E_D("replace into `ld_news_data` values('4','<span style=\"font-family: 微软雅黑\"><span style=\"font-size: 14px\"><span mso-ansi-language:=\"\" mso-bidi-language:=\"\" mso-bidi-theme-font:=\"\" mso-fareast-language:=\"\" mso-font-kerning:=\"\" new=\"\" times=\"\"><font color=\"#000000\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 销售人员能力难提高且流动性较大、稳定性较差，耐心不足，没有长久的、有效的客户跟踪方式和维护客户机制，导致客户&ldquo;流失率&rdquo;较大，又因为人才培养难，人才培训模式较难复制，所以极大地降低了&ldquo;成交率&rdquo;</font></span>。</span></span>','0','','0','0','','0','','0','1','|0');");
E_D("replace into `ld_news_data` values('5','<span mso-ansi-language:=\"\" mso-bidi-font-family:=\"\" mso-bidi-language:=\"\" mso-bidi-theme-font:=\"\" mso-fareast-language:=\"\" mso-font-kerning:=\"\" new=\"\" style=\"font-size: 12pt\" times=\"\"><font color=\"#000000\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"font-size: 14px\">市场竞争较激烈，投资与收效严重不平衡，效果好的投资大，投资小的效果差，投入效果不直观，事前难以衡量投资效果，影响&ldquo;客户到访量&rdquo;</span></font></span>','0','','0','0','','0','','0','1','|0');");
E_D("replace into `ld_news_data` values('6','<span mso-ansi-language:=\"\" mso-bidi-font-family:=\"\" mso-bidi-language:=\"\" mso-bidi-theme-font:=\"\" mso-fareast-language:=\"\" mso-font-kerning:=\"\" new=\"\" style=\"font-size: 12pt\" times=\"\"><font color=\"#000000\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 产品存在硬伤，同市场上的产品雷同较多，差异化不明显，缺乏吸引力，再加上学员报名积极性不高，严重影响了&ldquo;客户到访量和成交&rdquo;</font></span>','0','','0','0','','0','','0','1','|0');");
E_D("replace into `ld_news_data` values('7','&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 5月17日下午14:00-16:00 &ldquo;KI树德教育&rdquo;总裁兼董事长受邀校宝学院参加网略在线直播课程！<br />\r\n本次演讲主题为《招生中市场工作流程的设计》，其中全国的1000多名教育培训机构负责人兼校长聆听了本次的在线直播课程。凭借自己多年在市场中的实战经验KI总裁李老师主要就招生中存在的问题分享了自己的想法，并提供了一些意见和建议。<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 李老师是原某上市公司营销总监及商学院创始人，而且是国内管理培训泰斗余世维老师的首批弟子，现任多家企业特聘营销咨询顾问。本次直播课程虽然时间暂短，但内容丰富多彩，设计多个学科领域，包括日常生活中的与人沟通、日常生活交际礼仪、多场面灵活应对方式方法以及心理学、市场管理等方面，同时洞悉公司人事、薪酬、激励/考核及文化价值观等纯干货，有警示醒言等良句之姿。<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 校宝学院表示之后将会同李老师进行深度合作，期望在该平台上能展示出更多有关李老师的肺腑分享。下期系列李老师表示会很乐意在校宝平台上向广大校友聊一些相关的碎碎念，届时希望大家踊跃关注、相互沟通交流。<br />\r\n<br />\r\n&nbsp;&nbsp;&nbsp;<br />\r\n<strong>&nbsp;&nbsp; 注：<em>校宝学院</em>是基于互联网[免费、知识共享与碎片化学习]精神，连接120000多位培训机构校长和350000多位培训机构管理人员的免费在线直播课程</strong><br />\r\n<br />\r\n<br />\r\n','0','','0','0','','0','','0','1','|0');");
E_D("replace into `ld_news_data` values('8','<div class=\"dongTai_two_right clearFix\">\r\n<div class=\"dongTai_two_right_text fl\"><br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 4月初，当大家还在享受春天咋暖还寒的气候时，KI机器人又蠕蠕出洞了！一举签约了重庆优胜教育培训机构。双方就KI机器人正式入住重庆少儿优胜达成一致协议。同时聘请KI总裁李金昊担任重庆优胜教育机构常年营销顾问。就其未来的市场营销进行指导培训。<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 重庆优胜教育是专注于中小学学习指导的一对一教育培训机构。此次重庆少儿优胜教育引入了KI机器人初级课程之后，在5月份的招生统计中，平均客户到店量较4月份提高了4倍，除了KI机器人本身课程吸引了大量粉丝外，KI机器人初级课程的引进还为该机构主营业务增加了大量的销量，例如，奥数、语文以及数学课程等等也吸粉无数！业绩创新高！</div>\r\n</div>\r\n','0','','0','0','','0','','0','1','|0');");
E_D("replace into `ld_news_data` values('11','<div style=\"text-align: center\"><img src=\"/uploadfile/2017/0525/20170525051509906.jpg\" /></div>\r\n<br />\r\n','0','','0','0','','0','','0','1','|0');");
E_D("replace into `ld_news_data` values('9','<div style=\"text-align: center\"><span style=\"font-size: 14px\"><strong>珠联璧合</strong> <strong>共创企业未来</strong><br />\r\n<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &mdash;&mdash;树德教育与翰林轩教育签订合作</span><br />\r\n&nbsp;</div>\r\n<span style=\"font-size: 14px\">&nbsp;<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 5月初，翰林轩教育咨询服务有限责任公司与我司在北京进行了合作洽谈，并达成合作协议。<br />\r\n协议内容为聘请李金浩老师作为翰林轩教育的营销咨询顾问，同时引进了KI初级课程作为市场导流工具。<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 翰林轩教育咨询服务有限责任公司属于小区教育机构，主要开设书法、美术、英语课程。根据我们的数据统计，之前到店学习的学生比较少，但在引进了KI初级课程半个月之后，到店学员增加了10倍以上。报名机器人的学员非常火爆，另外还有很多学生报名了英语，美术，书法等课，教室空间和老师数量出现紧张，校方已安排联系扩充教室，新聘教师事项。<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;翰林轩教育表示希望能继续和我司合作后续开发的新课程。&nbsp;</span>','0','','0','0','','0','','0','1','|0');");
E_D("replace into `ld_news_data` values('10','<div style=\"text-align: center\"><strong>拥有合作</strong> <strong>拥抱成功</strong><br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &mdash;&mdash;树德教育与金智立签订合作</div>\r\n&nbsp;<br />\r\n5月初，金智立（北京）脑科学与教育中心与我司在北京进行了合作洽谈，并达成合作协议。<br />\r\n协议内容为聘请树德教育总裁李金浩作为金智立的营销咨询顾问，同时引进了KI初级课程作为市场导流工具。<br />\r\n金智立主要开设少儿全脑开发课程，位于北京海淀区金源商场附近，首次引流就放在金源商场内部，吸引了大量的孩子和家长的关注。<br />\r\n根据金智立老师提供的数据，统计了到店学员比以往增加了4倍，很多家长不仅给孩子报名了机器人课程，也报名了全脑开发的课程，校方表示教室空间已经不够使用，后期需要添加。并真诚的感谢李金浩老师，也希望继续和我司合作后续开发的课程。&nbsp;','0','','0','0','','0','','0','1','|0');");

require("../../inc/footer.php");
?>