<?php
require("../../inc/header.php");

/*
		SoftName : EmpireBak Version 2010
		Author   : wm_chief
		Copyright: Powered by www.phome.net
*/

DoSetDbChar('utf8');
E_D("DROP TABLE IF EXISTS `ld_category`;");
E_C("CREATE TABLE `ld_category` (
  `catid` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `siteid` smallint(5) unsigned NOT NULL DEFAULT '0',
  `module` varchar(15) NOT NULL,
  `type` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `modelid` smallint(5) unsigned NOT NULL DEFAULT '0',
  `parentid` smallint(5) unsigned NOT NULL DEFAULT '0',
  `arrparentid` varchar(255) NOT NULL,
  `child` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `arrchildid` mediumtext NOT NULL,
  `catname` varchar(30) NOT NULL,
  `catname_en` varchar(50) DEFAULT '',
  `style` varchar(5) NOT NULL,
  `image` varchar(100) NOT NULL,
  `description` mediumtext NOT NULL,
  `parentdir` varchar(100) NOT NULL,
  `catdir` varchar(30) NOT NULL,
  `url` varchar(100) NOT NULL,
  `items` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `hits` int(10) unsigned NOT NULL DEFAULT '0',
  `setting` mediumtext NOT NULL,
  `listorder` smallint(5) unsigned NOT NULL DEFAULT '0',
  `ismenu` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `sethtml` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `letter` varchar(30) NOT NULL,
  `usable_type` varchar(255) NOT NULL,
  PRIMARY KEY (`catid`,`catname`),
  KEY `module` (`module`,`parentid`,`listorder`,`catid`),
  KEY `siteid` (`siteid`,`type`)
) ENGINE=MyISAM AUTO_INCREMENT=43 DEFAULT CHARSET=utf8");
E_D("replace into `ld_category` values('1','1','content','0','3','0','0','1','1,34,29,30,31,32,33,36,37,38,39,40','课程介绍','Course Introduction','','/uploadfile/2017/0401/20170401102136748.jpg','','','Course','http://localhost/index.php?m=content&c=index&a=lists&catid=1','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category-course'',\n  ''list_template'' => ''list_course'',\n  ''show_template'' => ''show-course'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','1','1','0','kechengjieshao','');");
E_D("replace into `ld_category` values('2','1','content','0','1','0','0','1','2,3,4','招生服务','cor','','','<div class=\"heZuo_left fl\">\r\n<h4>Ki机器人课程</h4>\r\n<div class=\"odd clearFix\">\r\n<div class=\"diamond fl\">&nbsp;</div>\r\n<div class=\"odd_p fl\">零风险投资</div>\r\n</div>\r\n<div class=\"even clearFix\">\r\n<div class=\"diamond fl\">&nbsp;</div>\r\n<div class=\"even_p fl\">区域垄断，差异化竞争优势</div>\r\n</div>\r\n<div class=\"odd clearFix\">\r\n<div class=\"diamond fl\">&nbsp;</div>\r\n<div class=\"odd_p fl\">专业客服团队全天侯服务</div>\r\n</div>\r\n<div class=\"even clearFix\">\r\n<div class=\"diamond fl\">&nbsp;</div>\r\n<div class=\"even_p fl\">&ldquo;利益一体化&rdquo;合作模式，提供免费教学和销售培训支持。</div>\r\n</div>\r\n<div class=\"odd clearFix\">\r\n<div class=\"diamond fl\">&nbsp;</div>\r\n<div class=\"odd_p fl\">一次小额投资，持续可观回报。</div>\r\n</div>\r\n</div>\r\n<div class=\"heZuo_left heZuo_right fl\">\r\n<h4>其他机器人课程</h4>\r\n<div class=\"odd clearFix\">\r\n<div class=\"diamond fl\">&nbsp;</div>\r\n<div class=\"odd_p fl\">投资风险不确定性</div>\r\n</div>\r\n<div class=\"even clearFix\">\r\n<div class=\"diamond fl\">&nbsp;</div>\r\n<div class=\"even_p fl\">区域内类似产品繁多，竞争压力大</div>\r\n</div>\r\n<div class=\"odd clearFix\">\r\n<div class=\"diamond fl\">&nbsp;</div>\r\n<div class=\"odd_p fl\">有售前，没售后</div>\r\n</div>\r\n<div class=\"even clearFix\">\r\n<div class=\"diamond fl\">&nbsp;</div>\r\n<div class=\"even_p fl\">培训时间少，次数少，不系统，效果没保证。</div>\r\n</div>\r\n<div class=\"odd clearFix\">\r\n<div class=\"diamond fl\">&nbsp;</div>\r\n<div class=\"odd_p fl\">辛苦赚取的一点利润，却被反复收取了加盟费。</div>\r\n</div>\r\n</div>\r\n<div class=\"vs\">vs</div>\r\n','','cor','http://localhost/index.php?m=content&c=index&a=lists&catid=2','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','2','1','0','zhaoshengfuwu','');");
E_D("replace into `ld_category` values('3','1','content','1','0','2','0,2','0','3','合作说明  ','','','','','cor/','hzsm','http://localhost/index.php?m=content&c=index&a=lists&catid=3','0','0','array (\n  ''ishtml'' => ''0'',\n  ''template_list'' => '''',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => '''',\n  ''repeatchargedays'' => ''1'',\n)','3','1','0','hezuoshuoming  ','');");
E_D("replace into `ld_category` values('4','1','content','1','0','2','0,2','0','4','合作企业','joint venture','','/uploadfile/2017/0401/20170401102823107.jpg','','cor/','hzqy','http://localhost/index.php?m=content&c=index&a=lists&catid=4','0','0','array (\n  ''ishtml'' => ''0'',\n  ''template_list'' => '''',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => '''',\n  ''repeatchargedays'' => ''1'',\n)','4','1','0','hezuoqiye','');");
E_D("replace into `ld_category` values('5','1','content','0','3','0','0','1','5,6,41,18,19,20,21,22,23,42,7,8,9','会员服务','','','','','','service','http://localhost/index.php?m=content&c=index&a=lists&catid=5','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => '''',\n  ''list_template'' => '''',\n  ''show_template'' => '''',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','5','1','0','huiyuanfuwu','');");
E_D("replace into `ld_category` values('6','1','content','0','3','5','0,5','1','6,41,18,19,20,21,22,23,42','课程学习','','','','','service/','study','http://localhost/index.php?m=content&c=index&a=lists&catid=6','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category-study'',\n  ''list_template'' => ''list-study'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','6','1','0','kechengxuexi','');");
E_D("replace into `ld_category` values('7','1','content','1','0','5','0,5','0','7','比赛报名','','','','','service/','bsbm','http://localhost/index.php?m=content&c=index&a=lists&catid=7','0','0','array (\n  ''ishtml'' => ''0'',\n  ''template_list'' => '''',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => '''',\n  ''repeatchargedays'' => ''1'',\n)','7','1','0','bisaibaoming','');");
E_D("replace into `ld_category` values('8','1','content','0','3','5','0,5','0','8','专业认证','','','','','service/','zyrz','http://localhost/index.php?m=content&c=index&a=lists&catid=8','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','8','0','0','zhuanyerenzheng','');");
E_D("replace into `ld_category` values('9','1','content','0','3','5','0,5','0','9','VIP商学院','','','','','service/','vip','http://localhost/index.php?m=content&c=index&a=lists&catid=9','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => '''',\n  ''list_template'' => '''',\n  ''show_template'' => '''',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','9','1','0','vipshangxueyuan','');");
E_D("replace into `ld_category` values('10','1','content','0','1','0','0','1','10,11,12','企业概览','qygl','','','','','qygl','http://localhost/index.php?m=content&c=index&a=lists&catid=10','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','10','1','0','qiyegailan','');");
E_D("replace into `ld_category` values('11','1','content','1','0','10','0,10','0','11','公司介绍','','','','','qygl/','qyjs','http://localhost/index.php?m=content&c=index&a=lists&catid=11','0','0','array (\n  ''ishtml'' => ''0'',\n  ''template_list'' => '''',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => '''',\n  ''repeatchargedays'' => ''1'',\n)','11','1','0','gongsijieshao','');");
E_D("replace into `ld_category` values('12','1','content','1','0','10','0,10','0','12','企业文化','','','','','qygl/','qywh','http://localhost/index.php?m=content&c=index&a=lists&catid=12','0','0','array (\n  ''ishtml'' => ''0'',\n  ''template_list'' => '''',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => '''',\n  ''repeatchargedays'' => ''1'',\n)','12','1','0','qiyewenhua','');");
E_D("replace into `ld_category` values('13','1','content','0','1','0','0','0','13','企业动态','','','','','','qydt','http://localhost/index.php?m=content&c=index&a=lists&catid=13','4','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','13','1','0','qiyedongtai','');");
E_D("replace into `ld_category` values('14','1','content','0','1','0','0','1','14,16,17,15','联系我们','','','','','','lxwm','http://localhost/index.php?m=content&c=index&a=lists&catid=14','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','14','1','0','lianxiwomen','');");
E_D("replace into `ld_category` values('15','1','content','1','0','14','0,14','0','15','联系我们 ','','','','<ul class=\"lian_four clearFix\">\r\n<li><img src=\"/uploadfile/2017/0401/20170401055537660.jpg\" />\r\n<div class=\"lian_four_top\">公司地址</div>\r\n<div class=\"lian_four_bot\">北京市朝阳区朝阳北路145号13号楼4548号</div>\r\n</li>\r\n<li><img src=\"/uploadfile/2017/0401/20170401055551967.jpg\" />\r\n<div class=\"lian_four_top\">联系电话</div>\r\n<div class=\"lian_four_bot\">010-80541401</div>\r\n</li>\r\n<li><img src=\"/uploadfile/2017/0401/20170401055603237.jpg\" />\r\n<div class=\"lian_four_top\">邮编</div>\r\n<div class=\"lian_four_bot\">101149</div>\r\n</li>\r\n<li><img src=\"/uploadfile/2017/0401/20170401055615521.jpg\" />\r\n<div class=\"lian_four_top\">邮箱</div>\r\n<div class=\"lian_four_bot\">173466593@QQ.com</div>\r\n</li>\r\n</ul>\r\n','lxwm/','lxwms','http://localhost/index.php?m=content&c=index&a=lists&catid=15','0','0','array (\n  ''ishtml'' => ''0'',\n  ''template_list'' => '''',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => '''',\n  ''repeatchargedays'' => ''1'',\n)','17','1','0','lianxiwomen ','');");
E_D("replace into `ld_category` values('16','1','content','1','0','14','0,14','0','16','加盟留言','','','','','lxwm/','jmly','http://localhost/index.php?m=content&c=index&a=lists&catid=16','0','0','array (\n  ''ishtml'' => ''0'',\n  ''template_list'' => '''',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => '''',\n  ''repeatchargedays'' => ''1'',\n)','15','1','0','jiamengliuyan','');");
E_D("replace into `ld_category` values('17','1','content','1','0','14','0,14','0','17','诚聘英才','','','','','lxwm/','cpyc','http://localhost/index.php?m=content&c=index&a=lists&catid=17','0','0','array (\n  ''ishtml'' => ''0'',\n  ''template_list'' => '''',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => '''',\n  ''repeatchargedays'' => ''1'',\n)','16','1','0','chengpinyingcai','');");
E_D("replace into `ld_category` values('18','1','content','0','3','41','0,5,6,41','1','18,19,20','初级课程','','','/uploadfile/2017/0401/20170401042320385.jpg','我们每年会为会员机构无偿提供价值数万元的商学院服务。我们会特聘一些在培训行业内非常有经验的大咖，针对市场、销售、教学、服务、管理等一系列大家所关心的课题，举办为期数天的培训课程/论坛，以使大家在奋斗路上并不孤单，一边对标行业中的成功案例，把握方向的正确性；一边充电提高，以便开动更大马力前行。我们每年会为会员机构无偿提供价值数万元的商学院服务。我们会特聘一','service/study/jiqiren/','A','http://localhost/index.php?m=content&c=index&a=lists&catid=18','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category-study_2'',\n  ''list_template'' => ''list-study'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','18','1','0','chujikecheng','');");
E_D("replace into `ld_category` values('19','1','content','0','3','18','0,5,6,41,18','0','19','第一阶段 基础护理','','','/uploadfile/2017/0401/20170401093414523.png','我们每年会为会员机构无偿提供价值数万元的商学院服务。我们会特聘一些在培训行业内非常有经验的大咖，针对市场、销售、教学、服务、管理等一系列大家所关心的课题，举办为期数天的培训课程/论坛，以使大家在奋斗路上并不孤单，一边对标行业中的成功案例，把握方向的正确性；一边充电提高，以便开动更大马力前行。我们每年会为会员机构无偿提供价值数万元的商学院服务。我们会特聘一些在培训行业内非常有经验的大咖，针对市场、销售、教学、服务、管理等一系列大家所关心的课题，举办为期数天的培训课程/论坛，以使大家在奋斗路上并不孤单，一边对标行业中的成功案例，把握方向的正确性；一边充电提高，以便开动更大马力前行。我们每年会为会员机构无偿提供价值数万元的商学院服务。我们会特聘一些在培训行业内非常有经验的大咖，针对市场、销售、教学、服务、管理等一系列大家所关心的课题，举办为期数天的培训课程/论坛，以使大家在奋斗路上并不孤单，一边对标行业中的成功案例，把握方向的正确性；一边充电提高，以便开动更大马力前行。 项目/投资对接服务 我们每年会为会员机构提供项目/投资对接会，让企业不仅能从上下游中找到商机，更能使好项目对接到资本，加速企业融资发展。 中层管理培养服务 每年为会员机构提供中层管理课程的培训套餐，由500强企业的高管进行授课，以低廉价格享受高端培训课程。','service/study/jiqiren/A/','firsta','http://localhost/index.php?m=content&c=index&a=lists&catid=19','2','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category-study_2'',\n  ''list_template'' => ''list-study'',\n  ''show_template'' => ''show-study'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','19','1','0','diyijieduan jichuhuli','');");
E_D("replace into `ld_category` values('20','1','content','0','3','18','0,5,6,41,18','0','20','第二阶段的课程你知道吗','','','/uploadfile/2017/0401/20170401093431121.png','我们每年会为会员机构无偿提供价值数万元的商学院服务。我们会特聘一些在培训行业内非常有经验的大咖，针对市场、销售、教学、服务、管理等一系列大家所关心的课题，举办为期数天的培训课程/论坛，以使大家在奋斗路上并不孤单，一边对标行业中的成功案例，把握方向的正确性；一边充电提高，以便开动更大马力前行。我们每年会为会员机构无偿提供价值数万元的商学院服务。我们会特聘一些在培训行业内非常有经验的大咖，针对市场、销售、教学、服务、管理等一系列大家所关心的课题，举办为期数天的培训课程/论坛，以使大家在奋斗路上并不孤单，一边对标行业中的成功案例，把握方向的正确性；一边充电提高，以便开动更大马力前行。我们每年会为会员机构无偿提供价值数万元的商学院服务。我们会特聘一些在培训行业内非常有经验的大咖，针对市场、销售、教学、服务、管理等一系列大家所关心的课题，举办为期数天的培训课程/论坛，以使大家在奋斗路上并不孤单，一边对标行业中的成功案例，把握方向的正确性；一边充电提高，以便开动更大马力前行。 项目/投资对接服务 我们每年会为会员机构提供项目/投资对接会，让企业不仅能从上下游中找到商机，更能使好项目对接到资本，加速企业融资发展。 中层管理培养服务 每年为会员机构提供中层管理课程的培训套餐，由500强企业的高管进行授课，以低廉价格享受高端培训课程。','service/study/jiqiren/A/','Ab','http://localhost/index.php?m=content&c=index&a=lists&catid=20','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category-study_2'',\n  ''list_template'' => ''list-study'',\n  ''show_template'' => ''show-study'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','20','1','0','dierjieduandekechengnizhidaoma','');");
E_D("replace into `ld_category` values('21','1','content','0','3','41','0,5,6,41','1','21,22','中级课程','','','/uploadfile/2017/0401/20170401035508622.jpg','我们每年会为会员机构无偿提供价值数万元的商学院服务。我们会特聘一些在培训行业内非常有经验的大咖，针对市场、销售、教学、服务、管理等一系列大家所关心的课题，举办为期数天的培训课程/论坛，以使大家在奋斗路上并不孤单，一边对标行业中的成功案例，把握方向的正确性；一边充电提高，以便开动更大马力前行。我们每年会为会员机构无偿提供价值数万元的商学院服务。我们会特聘一','service/study/jiqiren/','B','http://localhost/index.php?m=content&c=index&a=lists&catid=21','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category-study_2'',\n  ''list_template'' => ''list-study'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','21','1','0','zhongjikecheng','');");
E_D("replace into `ld_category` values('22','1','content','0','3','21','0,5,6,41,21','0','22','第一阶段','','','','','service/study/jiqiren/B/','B1','http://localhost/index.php?m=content&c=index&a=lists&catid=22','1','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category-study'',\n  ''list_template'' => ''list-study'',\n  ''show_template'' => ''show-study'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','22','1','0','diyijieduan','');");
E_D("replace into `ld_category` values('23','1','content','0','3','41','0,5,6,41','0','23','高级课程','','','/uploadfile/2017/0401/20170401035731691.jpg','','service/study/jiqiren/','xy','http://localhost/index.php?m=content&c=index&a=lists&catid=23','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category-study_2'',\n  ''list_template'' => ''list-study'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','23','1','0','gaojikecheng','');");
E_D("replace into `ld_category` values('24','1','content','0','13','0','0','0','24','首页轮播','lb','','','','','lb','http://localhost/index.php?m=content&c=index&a=lists&catid=24','2','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','24','0','0','shouyelunbo','');");
E_D("replace into `ld_category` values('25','1','content','0','1','0','0','0','25','新闻动态','news','','','','','news','http://localhost/index.php?m=content&c=index&a=lists&catid=25','2','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','25','0','0','xinwendongtai','');");
E_D("replace into `ld_category` values('26','1','content','0','1','0','0','0','26','常见问题','common problem','','','','','problem','http://localhost/index.php?m=content&c=index&a=lists&catid=26','4','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','26','0','0','changjianwenti','');");
E_D("replace into `ld_category` values('27','1','content','0','3','0','0','0','27','课程介绍视频','video','','','','','video','http://localhost/index.php?m=content&c=index&a=lists&catid=27','2','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => '''',\n  ''list_template'' => '''',\n  ''show_template'' => '''',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','27','0','0','kechengjieshaoshipin','');");
E_D("replace into `ld_category` values('30','1','content','0','3','34','0,1,34','0','30','中级视频','','','/uploadfile/2017/0401/20170401120701334.jpg','KI初级课程 适合幼儿园及小学阶段的孩子学习','Course/jqr/','zhj','http://localhost/index.php?m=content&c=index&a=lists&catid=30','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category-course'',\n  ''list_template'' => ''list_course'',\n  ''show_template'' => ''show-course'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','30','1','0','zhongjishipin','');");
E_D("replace into `ld_category` values('29','1','content','0','3','34','0,1,34','0','29','初级课程','','','/uploadfile/2017/0401/20170401120701334.jpg','KI初级课程 适合幼儿园及小学阶段的孩子学习','Course/jqr/','A','http://localhost/index.php?m=content&c=index&a=lists&catid=29','4','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category-course'',\n  ''list_template'' => ''list_course'',\n  ''show_template'' => ''show-course'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','29','1','0','chujikecheng','');");
E_D("replace into `ld_category` values('31','1','content','0','3','34','0,1,34','0','31','高级视频','','','/uploadfile/2017/0401/20170401120701334.jpg','KI初级课程 适合幼儿园及小学阶段的孩子学习','Course/jqr/','gaoj','http://localhost/index.php?m=content&c=index&a=lists&catid=31','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category-course'',\n  ''list_template'' => ''list_course'',\n  ''show_template'' => ''show-course'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','31','1','0','gaojishipin','');");
E_D("replace into `ld_category` values('32','1','content','0','3','34','0,1,34','0','32','拓展课程','tz','','/uploadfile/2017/0401/20170401023009769.jpg','初级课程适合幼儿园及小学阶段的孩子学习。<br />\r\n通过CPU、马达、各类传感器及齿轮、滑轮等各种电子、物理器件的组合<br />\r\n运用把积木玩具通过简单的图形模块编程变成好玩的智能机器人。 ','Course/jqr/','tz','http://localhost/index.php?m=content&c=index&a=lists&catid=32','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category-course'',\n  ''list_template'' => ''list_course'',\n  ''show_template'' => ''show-course'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','32','1','0','tuozhankecheng','');");
E_D("replace into `ld_category` values('33','1','content','0','3','34','0,1,34','0','33','进阶课程','jingj','','/uploadfile/2017/0401/20170401023401299.jpg','初级课程适合幼儿园及小学阶段的孩子学习。<br />\r\n通过CPU、马达、各类传感器及齿轮、滑轮等各种电子、物理器件的组合<br />\r\n运用把积木玩具通过简单的图形模块编程变成好玩的智能机器人。 ','Course/jqr/','jingj','http://localhost/index.php?m=content&c=index&a=lists&catid=33','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category-course'',\n  ''list_template'' => ''list_course'',\n  ''show_template'' => ''show-course'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','33','1','0','jinjiekecheng','');");
E_D("replace into `ld_category` values('34','1','content','0','3','1','0,1','1','34,29,30,31,32,33','机器人系列','','','','KI中级课程适合小学阶段的孩子学习。','Course/','jqr','http://localhost/index.php?m=content&c=index&a=lists&catid=34','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category-course'',\n  ''list_template'' => ''list_course'',\n  ''show_template'' => ''show-course'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','34','1','0','jiqirenxilie','');");
E_D("replace into `ld_category` values('35','1','content','1','0','0','0','0','35','版权声明','copyright','','','','','copyright','http://localhost/index.php?m=content&c=index&a=lists&catid=35','0','0','array (\n  ''ishtml'' => ''0'',\n  ''template_list'' => '''',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => '''',\n  ''repeatchargedays'' => ''1'',\n)','35','0','0','banquanshengming','');");
E_D("replace into `ld_category` values('36','1','content','0','3','1','0,1','1','36,37,38,39,40','机器人同级系列','jqs','','','','Course/','jqs','http://localhost/index.php?m=content&c=index&a=lists&catid=36','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category-course'',\n  ''list_template'' => ''list_course'',\n  ''show_template'' => ''show-course'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','36','1','0','jiqirentongjixilie','');");
E_D("replace into `ld_category` values('37','1','content','0','3','36','0,1,36','0','37','3D打印课','3d','','','','Course/jqs/','3d','http://localhost/index.php?m=content&c=index&a=lists&catid=37','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category-course'',\n  ''list_template'' => ''list_course'',\n  ''show_template'' => ''show-course'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','37','1','0','3ddayinke','');");
E_D("replace into `ld_category` values('38','1','content','0','3','36','0,1,36','0','38','无人级航模课程','wuren','','','','Course/jqs/','wuren','http://localhost/index.php?m=content&c=index&a=lists&catid=38','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category-course'',\n  ''list_template'' => ''list_course'',\n  ''show_template'' => ''show-course'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','38','1','0','wurenjihangmokecheng','');");
E_D("replace into `ld_category` values('39','1','content','0','3','36','0,1,36','0','39','VR课程','vr','','','','Course/jqs/','vr','http://localhost/index.php?m=content&c=index&a=lists&catid=39','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category-course'',\n  ''list_template'' => ''list_course'',\n  ''show_template'' => ''show-course'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','39','1','0','vrkecheng','');");
E_D("replace into `ld_category` values('40','1','content','0','3','36','0,1,36','0','40','AR课程','AR课程','','','','Course/jqs/','AR','http://localhost/index.php?m=content&c=index&a=lists&catid=40','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category-course'',\n  ''list_template'' => ''list_course'',\n  ''show_template'' => ''show-course'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','40','1','0','arkecheng','');");
E_D("replace into `ld_category` values('41','1','content','0','3','6','0,5,6','1','41,18,19,20,21,22,23','机器人系列','jiqiren','','/uploadfile/2017/0502/20170502033759855.png','初级课程适合幼儿园及小学阶段的孩子学习。<br />\r\n通过CPU、马达、各类传感器及齿轮、滑轮等各种电子、物理器件的组合运用把积木玩具通过简单的图形模块编程变成好玩的智能机器人。','service/study/','jiqiren','http://localhost/index.php?m=content&c=index&a=lists&catid=41','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category-study'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','41','1','0','jiqirenxilie','');");
E_D("replace into `ld_category` values('42','1','content','0','3','6','0,5,6','0','42','B系列的课程','bsearize','','/uploadfile/2017/0502/20170502033934223.png','B阶段课程课程适合幼儿园及小学阶段的孩子学习。<br />\r\n通过CPU、马达、各类传感器及齿轮、滑轮等各种电子、物理器件的组合运用把积木玩具通过简单的图形模块编程变成好玩的智能机器人。','service/study/','bsearize','http://localhost/index.php?m=content&c=index&a=lists&catid=42','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','42','1','0','bxiliedekecheng','');");

require("../../inc/footer.php");
?>