<?php
return array (
  1 => 
  array (
    'catid' => '1',
    'parentid' => '0',
    'catname' => '课程合作',
    'siteid' => '1',
    'listorder' => '1',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=1&siteid=1',
    'status' => '1',
  ),
  111 => 
  array (
    'catid' => '111',
    'parentid' => '9',
    'catname' => '机器人系列',
    'siteid' => '1',
    'listorder' => '1',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=111&siteid=1',
    'status' => '1',
  ),
  109 => 
  array (
    'catid' => '109',
    'parentid' => '2',
    'catname' => '讲师介绍',
    'siteid' => '1',
    'listorder' => '1',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=109&siteid=1',
    'status' => '1',
  ),
  114 => 
  array (
    'catid' => '114',
    'parentid' => '111',
    'catname' => '初级课程',
    'siteid' => '1',
    'listorder' => '1',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=114&siteid=1',
    'status' => '1',
  ),
  125 => 
  array (
    'catid' => '125',
    'parentid' => '18',
    'catname' => 'KI初级课程招生培训',
    'siteid' => '1',
    'listorder' => '1',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=125&siteid=1',
    'status' => '1',
  ),
  29 => 
  array (
    'catid' => '29',
    'parentid' => '34',
    'catname' => '初级课程',
    'siteid' => '1',
    'listorder' => '1',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=29&siteid=1',
    'status' => '1',
  ),
  18 => 
  array (
    'catid' => '18',
    'parentid' => '41',
    'catname' => '初级课程',
    'siteid' => '1',
    'listorder' => '1',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=18&siteid=1',
    'status' => '1',
  ),
  6 => 
  array (
    'catid' => '6',
    'parentid' => '5',
    'catname' => '教师培训',
    'siteid' => '1',
    'listorder' => '1',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=6&siteid=1',
    'status' => '1',
  ),
  112 => 
  array (
    'catid' => '112',
    'parentid' => '9',
    'catname' => '创客系列',
    'siteid' => '1',
    'listorder' => '2',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=112&siteid=1',
    'status' => '1',
  ),
  73 => 
  array (
    'catid' => '73',
    'parentid' => '18',
    'catname' => 'KI初级课程预热课',
    'siteid' => '1',
    'listorder' => '2',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=73&siteid=1',
    'status' => '1',
  ),
  33 => 
  array (
    'catid' => '33',
    'parentid' => '34',
    'catname' => '进阶课程',
    'siteid' => '1',
    'listorder' => '2',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=33&siteid=1',
    'status' => '1',
  ),
  85 => 
  array (
    'catid' => '85',
    'parentid' => '2',
    'catname' => '咨              询',
    'siteid' => '1',
    'listorder' => '2',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=85&siteid=1',
    'status' => '1',
  ),
  49 => 
  array (
    'catid' => '49',
    'parentid' => '41',
    'catname' => '进阶课程',
    'siteid' => '1',
    'listorder' => '2',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=49&siteid=1',
    'status' => '1',
  ),
  115 => 
  array (
    'catid' => '115',
    'parentid' => '111',
    'catname' => '进阶课程',
    'siteid' => '1',
    'listorder' => '2',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=115&siteid=1',
    'status' => '1',
  ),
  2 => 
  array (
    'catid' => '2',
    'parentid' => '0',
    'catname' => '咨询培训',
    'siteid' => '1',
    'listorder' => '2',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=2&siteid=1',
    'status' => '1',
  ),
  9 => 
  array (
    'catid' => '9',
    'parentid' => '5',
    'catname' => '学习天地',
    'siteid' => '1',
    'listorder' => '2',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=9&siteid=1',
    'status' => '1',
  ),
  74 => 
  array (
    'catid' => '74',
    'parentid' => '18',
    'catname' => ' KI初级课程一阶段上',
    'siteid' => '1',
    'listorder' => '3',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=74&siteid=1',
    'status' => '1',
  ),
  113 => 
  array (
    'catid' => '113',
    'parentid' => '9',
    'catname' => '虚拟系列',
    'siteid' => '1',
    'listorder' => '3',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=113&siteid=1',
    'status' => '1',
  ),
  116 => 
  array (
    'catid' => '116',
    'parentid' => '111',
    'catname' => '中级课程',
    'siteid' => '1',
    'listorder' => '3',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=116&siteid=1',
    'status' => '1',
  ),
  30 => 
  array (
    'catid' => '30',
    'parentid' => '34',
    'catname' => '中级课程',
    'siteid' => '1',
    'listorder' => '3',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=30&siteid=1',
    'status' => '1',
  ),
  21 => 
  array (
    'catid' => '21',
    'parentid' => '41',
    'catname' => '中级课程',
    'siteid' => '1',
    'listorder' => '3',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=21&siteid=1',
    'status' => '1',
  ),
  76 => 
  array (
    'catid' => '76',
    'parentid' => '18',
    'catname' => 'KI初级课程一阶段下',
    'siteid' => '1',
    'listorder' => '4',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=76&siteid=1',
    'status' => '1',
  ),
  84 => 
  array (
    'catid' => '84',
    'parentid' => '41',
    'catname' => '拓展课程',
    'siteid' => '1',
    'listorder' => '4',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=84&siteid=1',
    'status' => '1',
  ),
  118 => 
  array (
    'catid' => '118',
    'parentid' => '111',
    'catname' => '拓展课程',
    'siteid' => '1',
    'listorder' => '4',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=118&siteid=1',
    'status' => '1',
  ),
  32 => 
  array (
    'catid' => '32',
    'parentid' => '34',
    'catname' => '拓展课程',
    'siteid' => '1',
    'listorder' => '4',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=32&siteid=1',
    'status' => '1',
  ),
  5 => 
  array (
    'catid' => '5',
    'parentid' => '0',
    'catname' => '会员服务',
    'siteid' => '1',
    'listorder' => '5',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=5&siteid=1',
    'status' => '1',
  ),
  77 => 
  array (
    'catid' => '77',
    'parentid' => '18',
    'catname' => 'KI初级课程二阶段上',
    'siteid' => '1',
    'listorder' => '5',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=77&siteid=1',
    'status' => '1',
  ),
  23 => 
  array (
    'catid' => '23',
    'parentid' => '41',
    'catname' => '高级课程',
    'siteid' => '1',
    'listorder' => '5',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=23&siteid=1',
    'status' => '1',
  ),
  117 => 
  array (
    'catid' => '117',
    'parentid' => '111',
    'catname' => '高级课程',
    'siteid' => '1',
    'listorder' => '5',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=117&siteid=1',
    'status' => '1',
  ),
  31 => 
  array (
    'catid' => '31',
    'parentid' => '34',
    'catname' => '高级课程',
    'siteid' => '1',
    'listorder' => '5',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=31&siteid=1',
    'status' => '1',
  ),
  78 => 
  array (
    'catid' => '78',
    'parentid' => '18',
    'catname' => 'KI初级课程二阶段下',
    'siteid' => '1',
    'listorder' => '6',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=78&siteid=1',
    'status' => '1',
  ),
  80 => 
  array (
    'catid' => '80',
    'parentid' => '18',
    'catname' => ' KI初级课程三阶段上',
    'siteid' => '1',
    'listorder' => '7',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=80&siteid=1',
    'status' => '1',
  ),
  81 => 
  array (
    'catid' => '81',
    'parentid' => '18',
    'catname' => ' KI初级课程三阶段下',
    'siteid' => '1',
    'listorder' => '8',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=81&siteid=1',
    'status' => '1',
  ),
  10 => 
  array (
    'catid' => '10',
    'parentid' => '0',
    'catname' => '企业概览',
    'siteid' => '1',
    'listorder' => '10',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=10&siteid=1',
    'status' => '1',
  ),
  13 => 
  array (
    'catid' => '13',
    'parentid' => '0',
    'catname' => '企业动态',
    'siteid' => '1',
    'listorder' => '13',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=13&siteid=1',
    'status' => '1',
  ),
  14 => 
  array (
    'catid' => '14',
    'parentid' => '0',
    'catname' => '联系我们',
    'siteid' => '1',
    'listorder' => '14',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=14&siteid=1',
    'status' => '1',
  ),
  34 => 
  array (
    'catid' => '34',
    'parentid' => '1',
    'catname' => '机器人系列',
    'siteid' => '1',
    'listorder' => '34',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=34&siteid=1',
    'status' => '1',
  ),
  36 => 
  array (
    'catid' => '36',
    'parentid' => '1',
    'catname' => '创客系列',
    'siteid' => '1',
    'listorder' => '36',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=36&siteid=1',
    'status' => '1',
  ),
  37 => 
  array (
    'catid' => '37',
    'parentid' => '36',
    'catname' => '3D打印课程',
    'siteid' => '1',
    'listorder' => '37',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=37&siteid=1',
    'status' => '1',
  ),
  38 => 
  array (
    'catid' => '38',
    'parentid' => '36',
    'catname' => '无人机航模课程',
    'siteid' => '1',
    'listorder' => '38',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=38&siteid=1',
    'status' => '1',
  ),
  41 => 
  array (
    'catid' => '41',
    'parentid' => '6',
    'catname' => '机器人系列',
    'siteid' => '1',
    'listorder' => '41',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=41&siteid=1',
    'status' => '1',
  ),
  42 => 
  array (
    'catid' => '42',
    'parentid' => '6',
    'catname' => '创客系列',
    'siteid' => '1',
    'listorder' => '42',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=42&siteid=1',
    'status' => '1',
  ),
  83 => 
  array (
    'catid' => '83',
    'parentid' => '1',
    'catname' => '虚拟系列',
    'siteid' => '1',
    'listorder' => '83',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=83&siteid=1',
    'status' => '1',
  ),
  88 => 
  array (
    'catid' => '88',
    'parentid' => '6',
    'catname' => '虚拟系列',
    'siteid' => '1',
    'listorder' => '88',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=88&siteid=1',
    'status' => '1',
  ),
  94 => 
  array (
    'catid' => '94',
    'parentid' => '42',
    'catname' => '3D打印课程',
    'siteid' => '1',
    'listorder' => '94',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=94&siteid=1',
    'status' => '1',
  ),
  96 => 
  array (
    'catid' => '96',
    'parentid' => '42',
    'catname' => '无人机航模课程',
    'siteid' => '1',
    'listorder' => '96',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=96&siteid=1',
    'status' => '1',
  ),
  97 => 
  array (
    'catid' => '97',
    'parentid' => '88',
    'catname' => 'VR课程',
    'siteid' => '1',
    'listorder' => '97',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=97&siteid=1',
    'status' => '1',
  ),
  98 => 
  array (
    'catid' => '98',
    'parentid' => '88',
    'catname' => 'AR课程',
    'siteid' => '1',
    'listorder' => '98',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=98&siteid=1',
    'status' => '1',
  ),
  99 => 
  array (
    'catid' => '99',
    'parentid' => '83',
    'catname' => 'VR课程',
    'siteid' => '1',
    'listorder' => '99',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=99&siteid=1',
    'status' => '1',
  ),
  100 => 
  array (
    'catid' => '100',
    'parentid' => '83',
    'catname' => 'AR课程',
    'siteid' => '1',
    'listorder' => '100',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=100&siteid=1',
    'status' => '1',
  ),
  110 => 
  array (
    'catid' => '110',
    'parentid' => '2',
    'catname' => '商务服务',
    'siteid' => '1',
    'listorder' => '110',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=110&siteid=1',
    'status' => '1',
  ),
  119 => 
  array (
    'catid' => '119',
    'parentid' => '112',
    'catname' => '3D打印课程',
    'siteid' => '1',
    'listorder' => '119',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=119&siteid=1',
    'status' => '1',
  ),
  120 => 
  array (
    'catid' => '120',
    'parentid' => '112',
    'catname' => '无人机航模课程',
    'siteid' => '1',
    'listorder' => '120',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=120&siteid=1',
    'status' => '1',
  ),
  121 => 
  array (
    'catid' => '121',
    'parentid' => '113',
    'catname' => 'VR课程',
    'siteid' => '1',
    'listorder' => '121',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=121&siteid=1',
    'status' => '1',
  ),
  122 => 
  array (
    'catid' => '122',
    'parentid' => '113',
    'catname' => 'AR课程',
    'siteid' => '1',
    'listorder' => '122',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=122&siteid=1',
    'status' => '1',
  ),
  123 => 
  array (
    'catid' => '123',
    'parentid' => '114',
    'catname' => '编程小任务图展',
    'siteid' => '1',
    'listorder' => '123',
    'type' => '0',
    'url' => 'http://www.shudeeducation.com/index.php?m=mobile&a=lists&catid=123&siteid=1',
    'status' => '1',
  ),
);
?>