<?php
require("../../inc/header.php");

/*
		SoftName : EmpireBak Version 2010
		Author   : wm_chief
		Copyright: Powered by www.phome.net
*/

DoSetDbChar('utf8');
E_D("DROP TABLE IF EXISTS `ld_category`;");
E_C("CREATE TABLE `ld_category` (
  `catid` smallint(5) unsigned NOT NULL auto_increment,
  `siteid` smallint(5) unsigned NOT NULL default '0',
  `module` varchar(15) NOT NULL,
  `type` tinyint(1) unsigned NOT NULL default '0',
  `modelid` smallint(5) unsigned NOT NULL default '0',
  `parentid` smallint(5) unsigned NOT NULL default '0',
  `arrparentid` varchar(255) NOT NULL,
  `child` tinyint(1) unsigned NOT NULL default '0',
  `arrchildid` mediumtext NOT NULL,
  `catname` varchar(30) NOT NULL,
  `catname_en` varchar(50) default '',
  `style` varchar(5) NOT NULL,
  `image` varchar(100) NOT NULL,
  `description` mediumtext NOT NULL,
  `parentdir` varchar(100) NOT NULL,
  `catdir` varchar(30) NOT NULL,
  `url` varchar(100) NOT NULL,
  `items` mediumint(8) unsigned NOT NULL default '0',
  `hits` int(10) unsigned NOT NULL default '0',
  `setting` mediumtext NOT NULL,
  `listorder` smallint(5) unsigned NOT NULL default '0',
  `ismenu` tinyint(1) unsigned NOT NULL default '1',
  `sethtml` tinyint(1) unsigned NOT NULL default '0',
  `letter` varchar(30) NOT NULL,
  `usable_type` varchar(255) NOT NULL,
  `icon` varchar(100) default NULL,
  `wapimage` varchar(100) NOT NULL,
  PRIMARY KEY  (`catid`,`catname`),
  KEY `module` (`module`,`parentid`,`listorder`,`catid`),
  KEY `siteid` (`siteid`,`type`)
) ENGINE=MyISAM AUTO_INCREMENT=59 DEFAULT CHARSET=utf8");
E_D("replace into `ld_category` values('1','1','content','0','3','0','0','1','1,34,29,30,31,33,32,36,37,38,39,40','课程介绍','Course Introduction','','/uploadfile/2017/0401/20170401102136748.jpg','','','Course','http://demo96.dfwlshy.com/index.php?m=content&c=index&a=lists&catid=1','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category-course'',\n  ''list_template'' => ''list_course'',\n  ''show_template'' => ''show-course'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','1','1','0','kechengjieshao','','','/uploadfile/2017/0513/20170513092825803.jpg');");
E_D("replace into `ld_category` values('2','1','content','0','1','0','0','1','2,3,4','招生服务','cor','','','<div class=\"heZuo_left fl\">\r\n<h4>Ki机器人课程</h4>\r\n<div class=\"odd clearFix\">\r\n<div class=\"diamond fl\">&nbsp;</div>\r\n<div class=\"odd_p fl\">零风险投资</div>\r\n</div>\r\n<div class=\"even clearFix\">\r\n<div class=\"diamond fl\">&nbsp;</div>\r\n<div class=\"even_p fl\">区域垄断，差异化竞争优势</div>\r\n</div>\r\n<div class=\"odd clearFix\">\r\n<div class=\"diamond fl\">&nbsp;</div>\r\n<div class=\"odd_p fl\">专业客服团队全天侯服务</div>\r\n</div>\r\n<div class=\"even clearFix\">\r\n<div class=\"diamond fl\">&nbsp;</div>\r\n<div class=\"even_p fl\">&ldquo;利益一体化&rdquo;合作模式，提供免费教学和销售培训支持。</div>\r\n</div>\r\n<div class=\"odd clearFix\">\r\n<div class=\"diamond fl\">&nbsp;</div>\r\n<div class=\"odd_p fl\">一次小额投资，持续可观回报。</div>\r\n</div>\r\n</div>\r\n<div class=\"heZuo_left heZuo_right fl\">\r\n<h4>其他机器人课程</h4>\r\n<div class=\"odd clearFix\">\r\n<div class=\"diamond fl\">&nbsp;</div>\r\n<div class=\"odd_p fl\">投资风险不确定性</div>\r\n</div>\r\n<div class=\"even clearFix\">\r\n<div class=\"diamond fl\">&nbsp;</div>\r\n<div class=\"even_p fl\">区域内类似产品繁多，竞争压力大</div>\r\n</div>\r\n<div class=\"odd clearFix\">\r\n<div class=\"diamond fl\">&nbsp;</div>\r\n<div class=\"odd_p fl\">有售前，没售后</div>\r\n</div>\r\n<div class=\"even clearFix\">\r\n<div class=\"diamond fl\">&nbsp;</div>\r\n<div class=\"even_p fl\">培训时间少，次数少，不系统，效果没保证。</div>\r\n</div>\r\n<div class=\"odd clearFix\">\r\n<div class=\"diamond fl\">&nbsp;</div>\r\n<div class=\"odd_p fl\">辛苦赚取的一点利润，却被反复收取了加盟费。</div>\r\n</div>\r\n</div>\r\n<div class=\"vs\">vs</div>\r\n','','cor','http://demo96.dfwlshy.com/index.php?m=content&c=index&a=lists&catid=2','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','2','1','0','zhaoshengfuwu','','','');");
E_D("replace into `ld_category` values('3','1','content','1','0','2','0,2','0','3','合作说明  ','','','','','cor/','hzsm','http://demo96.dfwlshy.com/index.php?m=content&c=index&a=lists&catid=3','0','0','array (\n  ''ishtml'' => ''0'',\n  ''template_list'' => '''',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => '''',\n  ''repeatchargedays'' => ''1'',\n)','3','1','0','hezuoshuoming  ','','','');");
E_D("replace into `ld_category` values('4','1','content','1','0','2','0,2','0','4','合作企业','joint venture','','/uploadfile/2017/0517/20170517105415876.png','','cor/','hzqy','http://demo96.dfwlshy.com/index.php?m=content&c=index&a=lists&catid=4','0','0','array (\n  ''ishtml'' => ''0'',\n  ''template_list'' => '''',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => '''',\n  ''repeatchargedays'' => ''1'',\n)','4','1','0','hezuoqiye','','','');");
E_D("replace into `ld_category` values('5','1','content','0','3','0','0','1','5,6,41,18,57,58,21,22,50,23,49,42,7,43,44,45,46,8,9','会员服务','','','','','','service','http://demo96.dfwlshy.com/index.php?m=content&c=index&a=lists&catid=5','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => '''',\n  ''list_template'' => '''',\n  ''show_template'' => '''',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','5','1','0','huiyuanfuwu','','','');");
E_D("replace into `ld_category` values('6','1','content','0','3','5','0,5','1','6,41,18,57,58,21,22,50,23,49,42','课程学习','','','','','service/','study','http://demo96.dfwlshy.com/index.php?m=content&c=index&a=lists&catid=6','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category-study'',\n  ''list_template'' => ''list-study'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','6','1','0','kechengxuexi','','','');");
E_D("replace into `ld_category` values('7','1','content','1','0','5','0,5','1','7,43,44,45,46','比赛报名','','','','','service/','bsbm','http://demo96.dfwlshy.com/index.php?m=content&c=index&a=lists&catid=7','0','0','array (\n  ''ishtml'' => ''0'',\n  ''template_list'' => ''default'',\n  ''page_template'' => ''page-match'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => '''',\n  ''repeatchargedays'' => ''1'',\n)','7','1','0','bisaibaoming','','','');");
E_D("replace into `ld_category` values('8','1','content','0','3','5','0,5','0','8','专业认证','','','','','service/','zyrz','http://demo96.dfwlshy.com/index.php?m=content&c=index&a=lists&catid=8','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','8','0','0','zhuanyerenzheng','','','');");
E_D("replace into `ld_category` values('9','1','content','0','3','5','0,5','0','9','VIP商学院','','','','','service/','vip','http://demo96.dfwlshy.com/index.php?m=content&c=index&a=lists&catid=9','1','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','9','1','0','vipshangxueyuan','','','');");
E_D("replace into `ld_category` values('10','1','content','0','1','0','0','1','10,11,12','企业概览','qygl','','','','','qygl','http://demo96.dfwlshy.com/index.php?m=content&c=index&a=lists&catid=10','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','10','1','0','qiyegailan','','','');");
E_D("replace into `ld_category` values('11','1','content','1','0','10','0,10','0','11','公司介绍','','','','','qygl/','qyjs','http://demo96.dfwlshy.com/index.php?m=content&c=index&a=lists&catid=11','0','0','array (\n  ''ishtml'' => ''0'',\n  ''template_list'' => '''',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => '''',\n  ''repeatchargedays'' => ''1'',\n)','11','1','0','gongsijieshao','','','');");
E_D("replace into `ld_category` values('12','1','content','1','0','10','0,10','0','12','企业文化','','','','','qygl/','qywh','http://demo96.dfwlshy.com/index.php?m=content&c=index&a=lists&catid=12','0','0','array (\n  ''ishtml'' => ''0'',\n  ''template_list'' => '''',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => '''',\n  ''repeatchargedays'' => ''1'',\n)','12','1','0','qiyewenhua','','','');");
E_D("replace into `ld_category` values('13','1','content','0','1','0','0','0','13','企业动态','','','','','','qydt','http://demo96.dfwlshy.com/index.php?m=content&c=index&a=lists&catid=13','4','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','13','1','0','qiyedongtai','','','');");
E_D("replace into `ld_category` values('14','1','content','0','1','0','0','1','14,16,17,15','联系我们','','','','','','lxwm','http://demo96.dfwlshy.com/index.php?m=content&c=index&a=lists&catid=14','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','14','1','0','lianxiwomen','','','');");
E_D("replace into `ld_category` values('15','1','content','1','0','14','0,14','0','15','联系我们 ','','','','<ul class=\"lian_four clearFix\">\r\n<li><img src=\"/uploadfile/2017/0401/20170401055537660.jpg\" />\r\n<div class=\"lian_four_top\">公司地址</div>\r\n<div class=\"lian_four_bot\">北京市朝阳区朝阳北路145号13号楼4548号</div>\r\n</li>\r\n<li><img src=\"/uploadfile/2017/0401/20170401055551967.jpg\" />\r\n<div class=\"lian_four_top\">联系电话</div>\r\n<div class=\"lian_four_bot\">010-80541401</div>\r\n</li>\r\n<li><img src=\"/uploadfile/2017/0401/20170401055603237.jpg\" />\r\n<div class=\"lian_four_top\">邮编</div>\r\n<div class=\"lian_four_bot\">101149</div>\r\n</li>\r\n<li><img src=\"/uploadfile/2017/0401/20170401055615521.jpg\" />\r\n<div class=\"lian_four_top\">邮箱</div>\r\n<div class=\"lian_four_bot\">173466593@QQ.com</div>\r\n</li>\r\n</ul>\r\n','lxwm/','lxwms','http://demo96.dfwlshy.com/index.php?m=content&c=index&a=lists&catid=15','0','0','array (\n  ''ishtml'' => ''0'',\n  ''template_list'' => ''default'',\n  ''page_template'' => ''page_lxwm'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => '''',\n  ''repeatchargedays'' => ''1'',\n)','17','1','0','lianxiwomen ','','','');");
E_D("replace into `ld_category` values('16','1','content','1','0','14','0,14','0','16','加盟留言','','','','','lxwm/','jmly','http://demo96.dfwlshy.com/index.php?m=content&c=index&a=lists&catid=16','0','0','array (\n  ''ishtml'' => ''0'',\n  ''template_list'' => ''default'',\n  ''page_template'' => ''page_jmlu'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => '''',\n  ''repeatchargedays'' => ''1'',\n)','15','1','0','jiamengliuyan','','','');");
E_D("replace into `ld_category` values('17','1','content','1','0','14','0,14','0','17','诚聘英才','','','','','lxwm/','cpyc','http://demo96.dfwlshy.com/index.php?m=content&c=index&a=lists&catid=17','0','0','array (\n  ''ishtml'' => ''0'',\n  ''template_list'' => '''',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => '''',\n  ''repeatchargedays'' => ''1'',\n)','16','1','0','chengpinyingcai','','','');");
E_D("replace into `ld_category` values('18','1','content','0','3','41','0,5,6,41','1','18,57,58','初级课程','','','/uploadfile/2017/0401/20170401042320385.jpg','我们每年会为会员机构无偿提供价值数万元的商学院服务。我们会特聘一些在培训行业内非常有经验的大咖，针对市场、销售、教学、服务、管理等一系列大家所关心的课题，举办为期数天的培训课程/论坛，以使大家在奋斗路上并不孤单，一边对标行业中的成功案例，把握方向的正确性；一边充电提高，以便开动更大马力前行。我们每年会为会员机构无偿提供价值数万元的商学院服务。我们会特聘一','service/study/jiqiren/','A','http://demo96.dfwlshy.com/index.php?m=content&c=index&a=lists&catid=18','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category-study_2'',\n  ''list_template'' => ''list-study'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','18','1','0','chujikecheng','','/uploadfile/2017/0508/20170508021452356.png','/uploadfile/2017/0512/20170512092226176.png');");
E_D("replace into `ld_category` values('57','1','content','0','3','18','0,5,6,41,18','0','57','预热课','','','/uploadfile/2017/0401/20170401042320385.jpg','我们每年会为会员机构无偿提供价值数万元的商学院服务。我们会特聘一些在培训行业内非常有经验的大咖，针对市场、销售、教学、服务、管理等一系列大家所关心的课题，举办为期数天的培训课程/论坛，以使大家在奋斗路上并不孤单，一边对标行业中的成功案例，把握方向的正确性；一边充电提高，以便开动更大马力前行。我们每年会为会员机构无偿提供价值数万元的商学院服务。我们会特聘一','service/study/jiqiren/A/','yure','http://demo96.dfwlshy.com/index.php?m=content&c=index&a=lists&catid=57','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list-study'',\n  ''show_template'' => ''show-study'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','57','1','0','yureke','','/uploadfile/2017/0508/20170508021452356.png','/uploadfile/2017/0512/20170512092226176.png');");
E_D("replace into `ld_category` values('58','1','content','0','3','18','0,5,6,41,18','0','58','一阶段 ','','','/uploadfile/2017/0401/20170401042320385.jpg','我们每年会为会员机构无偿提供价值数万元的商学院服务。我们会特聘一些在培训行业内非常有经验的大咖，针对市场、销售、教学、服务、管理等一系列大家所关心的课题，举办为期数天的培训课程/论坛，以使大家在奋斗路上并不孤单，一边对标行业中的成功案例，把握方向的正确性；一边充电提高，以便开动更大马力前行。我们每年会为会员机构无偿提供价值数万元的商学院服务。我们会特聘一','service/study/jiqiren/A/','yijieduan','http://demo96.dfwlshy.com/index.php?m=content&c=index&a=lists&catid=58','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list-study'',\n  ''show_template'' => ''show-study'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','58','1','0','yijieduan ','','/uploadfile/2017/0508/20170508021452356.png','/uploadfile/2017/0512/20170512092226176.png');");
E_D("replace into `ld_category` values('21','1','content','0','3','41','0,5,6,41','1','21,22,50','中级课程','','','/uploadfile/2017/0401/20170401035508622.jpg','我们每年会为会员机构无偿提供价值数万元的商学院服务。我们会特聘一些在培训行业内非常有经验的大咖，针对市场、销售、教学、服务、管理等一系列大家所关心的课题，举办为期数天的培训课程/论坛，以使大家在奋斗路上并不孤单，一边对标行业中的成功案例，把握方向的正确性；一边充电提高，以便开动更大马力前行。我们每年会为会员机构无偿提供价值数万元的商学院服务。我们会特聘一','service/study/jiqiren/','B','http://demo96.dfwlshy.com/index.php?m=content&c=index&a=lists&catid=21','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category-study_2'',\n  ''list_template'' => ''list-study'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','21','1','0','zhongjikecheng','','/uploadfile/2017/0509/20170509015125750.png','');");
E_D("replace into `ld_category` values('22','1','content','0','3','21','0,5,6,41,21','0','22','第一阶段','','','','','service/study/jiqiren/B/','B1','http://demo96.dfwlshy.com/index.php?m=content&c=index&a=lists&catid=22','3','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category-study'',\n  ''list_template'' => ''list-study'',\n  ''show_template'' => ''show-study'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','22','1','0','diyijieduan','','','');");
E_D("replace into `ld_category` values('23','1','content','0','3','41','0,5,6,41','0','23','高级课程','','','/uploadfile/2017/0401/20170401035731691.jpg','','service/study/jiqiren/','xy','http://demo96.dfwlshy.com/index.php?m=content&c=index&a=lists&catid=23','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category-study_2'',\n  ''list_template'' => ''list-study'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','23','1','0','gaojikecheng','','/uploadfile/2017/0509/20170509015153246.png','');");
E_D("replace into `ld_category` values('24','1','content','0','13','0','0','0','24','首页轮播','lb','','','','','lb','http://demo96.dfwlshy.com/index.php?m=content&c=index&a=lists&catid=24','2','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','24','0','0','shouyelunbo','','','');");
E_D("replace into `ld_category` values('25','1','content','0','1','0','0','0','25','新闻动态','news','','','','','news','http://demo96.dfwlshy.com/index.php?m=content&c=index&a=lists&catid=25','2','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','25','0','0','xinwendongtai','','','');");
E_D("replace into `ld_category` values('26','1','content','0','1','0','0','0','26','常见问题','common problem','','','','','problem','http://demo96.dfwlshy.com/index.php?m=content&c=index&a=lists&catid=26','4','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','26','0','0','changjianwenti','','','');");
E_D("replace into `ld_category` values('27','1','content','0','3','0','0','0','27','课程介绍视频','video','','','','','video','http://demo96.dfwlshy.com/index.php?m=content&c=index&a=lists&catid=27','3','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => '''',\n  ''list_template'' => '''',\n  ''show_template'' => '''',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','27','0','0','kechengjieshaoshipin','','','');");
E_D("replace into `ld_category` values('30','1','content','0','3','34','0,1,34','0','30','中级课程','','','/uploadfile/2017/0401/20170401120701334.jpg','中级课程适合小学阶段的孩子学习。<br />\r\n该课程的编程更加复杂，应用到的器件更加全面。如：触碰传感器、超声波传感器、陀螺仪传感器、光电传感器、中型、大型马达等，使机器人能实现的功能更加强大和智能化。<br />\r\n','Course/jqr/','zhj','http://demo96.dfwlshy.com/index.php?m=content&c=index&a=lists&catid=30','1','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category-course'',\n  ''list_template'' => ''list_course'',\n  ''show_template'' => ''show-course'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','30','1','0','zhongjikecheng','','','');");
E_D("replace into `ld_category` values('29','1','content','0','3','34','0,1,34','0','29','初级课程','','','/uploadfile/2017/0401/20170401120701334.jpg','初级课程适合幼儿园及小学阶段的孩子学习。<br />\r\n通过CPU、马达、各类传感器及齿轮、滑轮等各种电子、物理器件的组合运用，把积木玩具通过简单的图形模块编程变成好玩的智能机器人。<br />\r\n','Course/jqr/','A','http://demo96.dfwlshy.com/index.php?m=content&c=index&a=lists&catid=29','4','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category-course'',\n  ''list_template'' => ''list_course'',\n  ''show_template'' => ''show-course'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','29','1','0','chujikecheng','','','');");
E_D("replace into `ld_category` values('31','1','content','0','3','34','0,1,34','0','31','高级课程','','','/uploadfile/2017/0401/20170401120701334.jpg','适合中学阶段的孩子学习。<br />\r\n造型方面从之前的积木材料，变成了集成电路板，并加入了一些功能更加强大的传感器。如：压力、声音、湿度传感器等。编程也从简单的图形模块编程提高到了更为复杂的语言编程。<br />\r\n','Course/jqr/','gaoj','http://demo96.dfwlshy.com/index.php?m=content&c=index&a=lists&catid=31','1','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category-course'',\n  ''list_template'' => ''list_course'',\n  ''show_template'' => ''show-course'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','31','1','0','gaojikecheng','','','');");
E_D("replace into `ld_category` values('32','1','content','0','3','34','0,1,34','0','32','拓展课程','tz','','/uploadfile/2017/0401/20170401023009769.jpg','初级课程适合幼儿园及小学阶段的孩子学习。<br />\r\n通过CPU、马达、各类传感器及齿轮、滑轮等各种电子、物理器件的组合<br />\r\n运用把积木玩具通过简单的图形模块编程变成好玩的智能机器人。 ','Course/jqr/','tz','http://demo96.dfwlshy.com/index.php?m=content&c=index&a=lists&catid=32','1','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category-course'',\n  ''list_template'' => ''list_course'',\n  ''show_template'' => ''show-course'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','33','1','0','tuozhankecheng','','','');");
E_D("replace into `ld_category` values('33','1','content','0','3','34','0,1,34','0','33','进阶课程','jingj','','/uploadfile/2017/0401/20170401023401299.jpg','初级课程适合幼儿园及小学阶段的孩子学习。<br />\r\n通过CPU、马达、各类传感器及齿轮、滑轮等各种电子、物理器件的组合<br />\r\n运用把积木玩具通过简单的图形模块编程变成好玩的智能机器人。 ','Course/jqr/','jingj','http://demo96.dfwlshy.com/index.php?m=content&c=index&a=lists&catid=33','1','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category-course'',\n  ''list_template'' => ''list_course'',\n  ''show_template'' => ''show-course'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','32','1','0','jinjiekecheng','','','');");
E_D("replace into `ld_category` values('34','1','content','0','3','1','0,1','1','34,29,30,31,33,32','机器人系列','','','','初级课程适合幼儿园及小学阶段的孩子学习。<br />\r\n通过CPU、马达、各类传感器及齿轮、滑轮等各种电子、物理器件的组合运用，把积木玩具通过简单的图形模块编程变成好玩的智能机器人。<br />\r\n','Course/','jqr','http://demo96.dfwlshy.com/index.php?m=content&c=index&a=lists&catid=34','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category-course'',\n  ''list_template'' => ''list_course'',\n  ''show_template'' => ''show-course'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','34','1','0','jiqirenxilie','','','');");
E_D("replace into `ld_category` values('35','1','content','1','0','0','0','0','35','版权声明','copyright','','','','','copyright','http://demo96.dfwlshy.com/index.php?m=content&c=index&a=lists&catid=35','0','0','array (\n  ''ishtml'' => ''0'',\n  ''template_list'' => '''',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => '''',\n  ''repeatchargedays'' => ''1'',\n)','35','0','0','banquanshengming','','','');");
E_D("replace into `ld_category` values('36','1','content','0','3','1','0,1','1','36,37,38,39,40','创客系列','jqs','','','','Course/','jqs','http://demo96.dfwlshy.com/index.php?m=content&c=index&a=lists&catid=36','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category-course'',\n  ''list_template'' => ''list_course'',\n  ''show_template'' => ''show-course'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','36','1','0','chuangkexilie','','','');");
E_D("replace into `ld_category` values('37','1','content','0','3','36','0,1,36','0','37','3D打印课','3d','','/uploadfile/2017/0519/20170519102958104.jpg','适合小学阶段的孩子学习。<br />\r\n以数字模型文件为基础进行设计，运用粉末状金属或塑料等材料，通过逐层打印的方式来构造3D物体，是一门培养孩子创意和科学素养的科技课程。','Course/jqs/','3d','http://demo96.dfwlshy.com/index.php?m=content&c=index&a=lists&catid=37','1','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category-course'',\n  ''list_template'' => ''list_course'',\n  ''show_template'' => ''show-course'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','37','1','0','3ddayinke','','','');");
E_D("replace into `ld_category` values('38','1','content','0','3','36','0,1,36','0','38','无人级航模课程','wuren','','/uploadfile/2017/0519/20170519103030222.jpg','适合小学阶段的孩子学习。<br />\r\n以数字模型文件为基础进行设计，运用粉末状金属或塑料等材料，通过逐层打印的方式来构造3D物体，是一门培养孩子创意和科学素养的科技课程。','Course/jqs/','wuren','http://demo96.dfwlshy.com/index.php?m=content&c=index&a=lists&catid=38','1','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category-course'',\n  ''list_template'' => ''list_course'',\n  ''show_template'' => ''show-course'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','38','1','0','wurenjihangmokecheng','','','');");
E_D("replace into `ld_category` values('39','1','content','0','3','36','0,1,36','0','39','VR课程','vr','','/uploadfile/2017/0519/20170519102958104.jpg','适合小学阶段的孩子学习。<br />\r\n以数字模型文件为基础进行设计，运用粉末状金属或塑料等材料，通过逐层打印的方式来构造3D物体，是一门培养孩子创意和科学素养的科技课程。','Course/jqs/','vr','http://demo96.dfwlshy.com/index.php?m=content&c=index&a=lists&catid=39','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category-course'',\n  ''list_template'' => ''list_course'',\n  ''show_template'' => ''show-course'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','39','1','0','vrkecheng','','','');");
E_D("replace into `ld_category` values('40','1','content','0','3','36','0,1,36','0','40','AR课程','AR课程','','/uploadfile/2017/0519/20170519103030222.jpg','适合小学阶段的孩子学习。<br />\r\n以数字模型文件为基础进行设计，运用粉末状金属或塑料等材料，通过逐层打印的方式来构造3D物体，是一门培养孩子创意和科学素养的科技课程。','Course/jqs/','AR','http://demo96.dfwlshy.com/index.php?m=content&c=index&a=lists&catid=40','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category-course'',\n  ''list_template'' => ''list_course'',\n  ''show_template'' => ''show-course'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','40','1','0','arkecheng','','','');");
E_D("replace into `ld_category` values('41','1','content','0','3','6','0,5,6','1','41,18,57,58,21,22,50,23,49','机器人系列','jiqiren','','/uploadfile/2017/0502/20170502033759855.png','初级课程适合幼儿园及小学阶段的孩子学习。<br />\r\n通过CPU、马达、各类传感器及齿轮、滑轮等各种电子、物理器件的组合运用把积木玩具通过简单的图形模块编程变成好玩的智能机器人。','service/study/','jiqiren','http://demo96.dfwlshy.com/index.php?m=content&c=index&a=lists&catid=41','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category-study1'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','41','1','0','jiqirenxilie','','','/uploadfile/2017/0512/20170512092226176.png');");
E_D("replace into `ld_category` values('42','1','content','0','3','6','0,5,6','0','42','B系列的课程','bsearize','','/uploadfile/2017/0502/20170502033934223.png','B阶段课程课程适合幼儿园及小学阶段的孩子学习。<br />\r\n通过CPU、马达、各类传感器及齿轮、滑轮等各种电子、物理器件的组合运用把积木玩具通过简单的图形模块编程变成好玩的智能机器人。','service/study/','bsearize','http://demo96.dfwlshy.com/index.php?m=content&c=index&a=lists&catid=42','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category-study1'',\n  ''list_template'' => ''list-study'',\n  ''show_template'' => ''show-study'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','42','1','0','bxiliedekecheng','','','');");
E_D("replace into `ld_category` values('43','1','content','1','0','7','0,5,7','0','43','FLL世界杯比赛','FLL','','','<div class=\"match_bot_text\">\r\n<div class=\"match_bot_text_title\">一.比赛简介</div>\r\nFIRST机器人挑战赛（FIRST Robotics Competition）是由美国非盈利机构FIRST主办，针对高中生、大专生的一项工业级机器人竞赛，把运动的刺激性和科学技术的精确结合在一起，被称作&ldquo;智力上的大学运动会&rdquo;。该项赛事已经获得全球500多所高校的认可，所有参赛队员每年均可获得申请总额约3000万美元奖学金的机会，如美国麻省理工大学、哥伦比亚大学、加拿大的多伦多大学、澳大利亚的麦考瑞大学等。每年都会有更多新的大学加入到FIRST奖学金名单中。 &nbsp; &nbsp; &nbsp;FIRST机器人挑战赛在全球有3000多家赞助商，其中不乏国际知名企业，包括全球赛事启动赞助商美国国家宇航局（NASA）和美国参数技术公司（PTC）、Google、NI、AndyMark、Microsoft等。\r\n<div class=\"match_bot_text_title2\">FRC赛制介绍</div>\r\nFRC比赛截止到2014年已经在美国举办了23届。全球队伍2000多支，遍及美国49个州，4个省和13个国家和地区。每年4月，FRC世锦赛都会在美国圣路易斯举行，届时，有来自中国、美国、英国、澳大利亚、巴西、加拿大、智利 、多米尼加共和国、德国、以色列、墨西哥、土耳其等十几个国家和地区的队伍参加比赛。<br />\r\nFRC比赛，是一个开放的国际平台。每年1月初，FIRST公布新主题；1、2月，是队伍搭建机器人的时间。</div>\r\n<div class=\"match_ul_box\">\r\n<ul class=\"match_ul clearFix\">\r\n<li><img src=\"/uploadfile/2017/0509/20170509122411212.png\" /></li>\r\n<li><img src=\"/uploadfile/2017/0509/20170509122427104.png\" /></li>\r\n</ul>\r\n</div>\r\n','service/bsbm/','FLL','http://demo96.dfwlshy.com/index.php?m=content&c=index&a=lists&catid=43','0','0','array (\n  ''ishtml'' => ''0'',\n  ''template_list'' => '''',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => '''',\n  ''repeatchargedays'' => ''1'',\n)','43','1','0','fllshijiebeibisai','','','');");
E_D("replace into `ld_category` values('44','1','content','1','0','7','0,5,7','0','44','FRC世界杯挑战赛','FRC','','','<div class=\"match_bot_text\">\r\n<div class=\"match_bot_text_title\">一.比赛简介</div>\r\nFIRST机器人挑战赛（FIRST Robotics Competition）是由美国非盈利机构FIRST主办，针对高中生、大专生的一项工业级机器人竞赛，把运动的刺激性和科学技术的精确结合在一起，被称作&ldquo;智力上的大学运动会&rdquo;。该项赛事已经获得全球500多所高校的认可，所有参赛队员每年均可获得申请总额约3000万美元奖学金的机会，如美国麻省理工大学、哥伦比亚大学、加拿大的多伦多大学、澳大利亚的麦考瑞大学等。每年都会有更多新的大学加入到FIRST奖学金名单中。 &nbsp; &nbsp; &nbsp;FIRST机器人挑战赛在全球有3000多家赞助商，其中不乏国际知名企业，包括全球赛事启动赞助商美国国家宇航局（NASA）和美国参数技术公司（PTC）、Google、NI、AndyMark、Microsoft等。\r\n<div class=\"match_bot_text_title2\">FRC赛制介绍</div>\r\nFRC比赛截止到2014年已经在美国举办了23届。全球队伍2000多支，遍及美国49个州，4个省和13个国家和地区。每年4月，FRC世锦赛都会在美国圣路易斯举行，届时，有来自中国、美国、英国、澳大利亚、巴西、加拿大、智利 、多米尼加共和国、德国、以色列、墨西哥、土耳其等十几个国家和地区的队伍参加比赛。<br />\r\nFRC比赛，是一个开放的国际平台。每年1月初，FIRST公布新主题；1、2月，是队伍搭建机器人的时间。</div>\r\n<div class=\"match_ul_box\">\r\n<ul class=\"match_ul clearFix\">\r\n<li><img src=\"/uploadfile/2017/0510/20170510112550236.png\" /></li>\r\n<li><img src=\"/uploadfile/2017/0510/20170510112600373.png\" /></li>\r\n</ul>\r\n</div>\r\n\r\n','service/bsbm/','FRC','http://demo96.dfwlshy.com/index.php?m=content&c=index&a=lists&catid=44','0','0','array (\n  ''ishtml'' => ''0'',\n  ''template_list'' => ''default'',\n  ''page_template'' => ''page'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => '''',\n  ''repeatchargedays'' => ''1'',\n)','44','1','0','frcshijiebeitiaozhansai','','','');");
E_D("replace into `ld_category` values('45','1','content','1','0','7','0,5,7','0','45','FTC世界杯比赛','FTC','','','<div class=\"match_bot_text\">\r\n<div class=\"match_bot_text_title\">一.比赛简介</div>\r\nFIRST 科技挑战赛（FTC）于2007年FTC正式成为FIRST项目中的一员。是FIRST系列的最新项目。<br />\r\nFTC（FIRST Tech Challenge） 机器人科技挑战赛是由美国FIRST非盈利性机构主办的针对12-18岁高中生的国际性机器人比赛。现今每年约 250,000名高中生参加。美国麻省理工大学每9个学生中就有1个参加过FIRST比赛。<br />\r\nFTC比赛可设计性强、创造性强，基于遥控操作，给学生提供了一个平台，把课堂上的科技概念运用到现实工程师问题解决中 。学生面对无尽挑战，创造特有的解决方案，同时培养团队合作、演讲技能、商业意识。MATRIX是FTC比赛的指定使用器材。<br />\r\n2011年FTC在中国的国际学校试点赛成功举办。<br />\r\n2012年开始在中国正式举办：40支队伍参加。成都市第七中学、上海市格致中学和北京市西城区科技馆代表中国赛区于2012年4月在美国参加FTC世界锦标赛。在国内院校中掀起了机器人设计热潮。\r\n<div class=\"match_ul_box\">\r\n<ul class=\"match_ul clearFix\">\r\n<li><img src=\"/uploadfile/2017/0510/20170510105120485.png\" /></li>\r\n<li><img src=\"/uploadfile/2017/0510/20170510105131707.png\" /></li>\r\n</ul>\r\n</div>\r\n</div>\r\n','service/bsbm/','FTC','http://demo96.dfwlshy.com/index.php?m=content&c=index&a=lists&catid=45','0','0','array (\n  ''ishtml'' => ''0'',\n  ''template_list'' => ''default'',\n  ''page_template'' => ''page'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => '''',\n  ''repeatchargedays'' => ''1'',\n)','45','1','0','ftcshijiebeibisai','','','');");
E_D("replace into `ld_category` values('46','1','content','1','0','7','0,5,7','0','46','JR.FLL世界杯比赛','JR.FLL','','','<div class=\"match_bot_text\">\r\n<div class=\"match_bot_text_title\">一.比赛简介</div>\r\nr. FLL为 Junior FIRST LEGO League简称，是美国FRIST非盈利慈善性机构举办的低年龄孩子们的国际活动，活动为Jr. FLL的队伍提供了一个展示工作成果以及和其他对科学和技术感兴趣的小朋友见面交流的机会和平台。<br />\r\nJr. FLL将现实世界的事物与动手做活动相结合，放手让5-8岁的孩子们去发现解决问题的方法，并获得那些当今科学家和工程师们所面对的机会。Jr. FLL坚信，孩子们与生俱来的好奇心和创造力对于预见机遇和开发创新性方案是至关重要的品质。通过鼓励孩子们发挥想象力，同时利用所学到的技术检验理论，并创造出解决问题的办法，FLL的活动满足了孩子们现阶段的需求，也有助于他们对科学技术形成正确的理解。\r\n<div class=\"match_bot_text match_bot_text2\">\r\n<div class=\"match_bot_text_title\">二.比赛核心价值</div>\r\n我们是一个团队。<br />\r\n1 .我们在教练和辅导员的指导下，自己努力地去寻找问题的解决方案。</div>\r\n<div class=\"match_ul_box\">\r\n<ul class=\"match_ul clearFix\">\r\n<li><img src=\"/uploadfile/2017/0510/20170510111326821.png\" /></li>\r\n<li><img src=\"/uploadfile/2017/0510/20170510111337167.png\" /></li>\r\n</ul>\r\n</div>\r\n</div>\r\n','service/bsbm/','JRFLL','http://demo96.dfwlshy.com/index.php?m=content&c=index&a=lists&catid=46','0','0','array (\n  ''ishtml'' => ''0'',\n  ''template_list'' => ''default'',\n  ''page_template'' => ''page'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => '''',\n  ''repeatchargedays'' => ''1'',\n)','46','1','0','jr.fllshijiebeibisai','','','');");
E_D("replace into `ld_category` values('47','1','content','0','13','0','0','0','47','手机版轮播','wapbanner','','','','','wapbanner','http://demo96.dfwlshy.com/index.php?m=content&c=index&a=lists&catid=47','1','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','47','0','0','shoujibanlunbo','','','');");
E_D("replace into `ld_category` values('49','1','content','0','3','41','0,5,6,41','0','49','进级课程','jinq','','/uploadfile/2017/0502/20170502033759855.png','初级课程适合幼儿园及小学阶段的孩子学习。<br />\r\n通过CPU、马达、各类传感器及齿轮、滑轮等各种电子、物理器件的组合运用把积木玩具通过简单的图形模块编程变成好玩的智能机器人。','service/study/jiqiren/','jin','http://demo96.dfwlshy.com/index.php?m=content&c=index&a=lists&catid=49','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => '''',\n  ''list_template'' => '''',\n  ''show_template'' => '''',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','49','1','0','jinjikecheng','','','/uploadfile/2017/0512/20170512092226176.png');");
E_D("replace into `ld_category` values('50','1','content','0','3','21','0,5,6,41,21','0','50','第二阶段','','','/uploadfile/2017/0401/20170401035508622.jpg','我们每年会为会员机构无偿提供价值数万元的商学院服务。我们会特聘一些在培训行业内非常有经验的大咖，针对市场、销售、教学、服务、管理等一系列大家所关心的课题，举办为期数天的培训课程/论坛，以使大家在奋斗路上并不孤单，一边对标行业中的成功案例，把握方向的正确性；一边充电提高，以便开动更大马力前行。我们每年会为会员机构无偿提供价值数万元的商学院服务。我们会特聘一','service/study/jiqiren/B/','wang','http://demo96.dfwlshy.com/index.php?m=content&c=index&a=lists&catid=50','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => '''',\n  ''list_template'' => '''',\n  ''show_template'' => '''',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','50','1','0','dierjieduan','','/uploadfile/2017/0509/20170509015125750.png','');");

require("../../inc/footer.php");
?>